config/routes.rb
Rails.application.routes.draw do
  resources :mistake_users
  resources :templates
  resources :users
  resources :mistakes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "mistakes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mistake.rb
class Mistake < ApplicationRecord
    has_many :mistake_users
    has_many :users, through: :mistake_users
end

app/models/mistake_user.rb
class MistakeUser < ApplicationRecord
    belongs_to :user
    belongs_to :mistake
end

app/models/user.rb
class User < ApplicationRecord
    has_many :mistake_users
    has_many :mistakes, through: :mistake_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mistake_users_controller.rb
class MistakeUsersController < ApplicationController
  before_action :set_mistake_user, only: %i[ show edit update destroy ]

  # GET /mistake_users or /mistake_users.json
  def index
    @mistake_users = MistakeUser.all
  end

  # GET /mistake_users/1 or /mistake_users/1.json
  def show
  end

  # GET /mistake_users/new
  def new
    @mistake_user = MistakeUser.new
  end

  # GET /mistake_users/1/edit
  def edit
  end

  # POST /mistake_users or /mistake_users.json
  def create
    @mistake_user = MistakeUser.new(mistake_user_params)

    respond_to do |format|
      if @mistake_user.save
        format.html { redirect_to mistake_user_url(@mistake_user), notice: "Mistake user was successfully created." }
        format.json { render :show, status: :created, location: @mistake_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mistake_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mistake_users/1 or /mistake_users/1.json
  def update
    respond_to do |format|
      if @mistake_user.update(mistake_user_params)
        format.html { redirect_to mistake_user_url(@mistake_user), notice: "Mistake user was successfully updated." }
        format.json { render :show, status: :ok, location: @mistake_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mistake_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mistake_users/1 or /mistake_users/1.json
  def destroy
    @mistake_user.destroy!

    respond_to do |format|
      format.html { redirect_to mistake_users_url, notice: "Mistake user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mistake_user
      @mistake_user = MistakeUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mistake_user_params
      params.require(:mistake_user).permit(:user_id, :mistake_id)
    end
end

app/controllers/mistakes_controller.rb
class MistakesController < ApplicationController
  before_action :set_mistake, only: %i[ show edit update destroy ]

  # GET /mistakes or /mistakes.json
  def index
    @mistakes = Mistake.all
    respond_to do |format|
      format.html
      format.json { render json: MistakesDatatable.new(view_context)}
    end
  end

  # GET /mistakes/1 or /mistakes/1.json
  def show
    @mistake = Mistake.find(params[:id])
  end

  # GET /mistakes/new
  def new
    @mistake = Mistake.new
  end

  # GET /mistakes/1/edit
  def edit
  end

  # POST /mistakes or /mistakes.json
  def create
    @mistake = Mistake.new(mistake_params)

    respond_to do |format|
      if @mistake.save
        format.html { redirect_to mistake_url(@mistake), notice: "Mistake was successfully created." }
        format.json { render :show, status: :created, location: @mistake }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mistake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mistakes/1 or /mistakes/1.json
  def update
    respond_to do |format|
      if @mistake.update(mistake_params)
        format.html { redirect_to mistake_url(@mistake), notice: "Mistake was successfully updated." }
        format.json { render :show, status: :ok, location: @mistake }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mistake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mistakes/1 or /mistakes/1.json
  def destroy
    @mistake.mistake_users.destroy_all
    @mistake.destroy!

    respond_to do |format|
      format.html { redirect_to mistakes_url, notice: "Mistake was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mistake
      @mistake = Mistake.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mistake_params
      params.require(:mistake).permit(:name, :description, :severity)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]


  # GET /users or /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: UsersDatatable.new(view_context) }
    end
  end
  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end
  # GET /users/new
  def new
    @user = User.new
  end
  # GET /users/1/edit
  def edit
  end
  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /users/1 or /users/1.json
  def destroy
    @user.mistake_users.destroy_all
    @user.destroy!
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mistake_users_helper.rb
module MistakeUsersHelper
end

app/helpers/mistakes_helper.rb
module MistakesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MistakesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
    <nav class="navbar navbar-default navbar-expand-sm">
      <div class="container-fluid">
        <div class="row">
          <ul class="nav navbar-items">
            <li class="navbar-item active">
              <img class="d-inline-block align-top" src="/assets/Error icon.png"
                  width="50" height="50" >
              <%= link_to 'Log It!', root_path, class: "navbar-brand" %>
            </li>
            <li class="navbar-item active">
            <%= link_to 'Users', users_path, class: "navbar-brand" %>
            </li>
            <li class="navbar-item active">
            <%= link_to "Add Log", new_mistake_user_path, class: "navbar-brand" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/mistake_users/_form.html.erb
<%= form_with(model: mistake_user) do |f| %>
  <% if mistake_user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mistake_user.errors.count, "error") %> prohibited this mistake_user from being saved:</h2>

      <ul>
        <% mistake_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-1"><%= f.label :user_id , "User's Email" %></div>
    <div class="col-sm-4"><%=f.select :user_id, options_from_collection_for_select(User.all, :id, :email, f.object.user_id), { include_blank: 'Select User Name'}, class: "form-control" %></div>
  </div><br>
   <div class="row">
    <div class="col-sm-1"><%= f.label :mistake_id, "Mistake Type"%></div>
    <div class="col-sm-4"><%= f.select :mistake_id, options_from_collection_for_select(Mistake.all, :id, :name, f.object.mistake_id), { include_blank: 'Select User Name'}, class: "form-control" %></div>
  </div><br>

  <div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/mistake_users/_mistake_user.html.erb
<div id="<%= dom_id mistake_user %>">
</div>

app/views/mistake_users/edit.html.erb
<h1>Editing mistake user</h1>

<%= render "form", mistake_user: @mistake_user %>

<br>

<div>
  <%= link_to "Show this mistake user", @mistake_user %> |
  <%= link_to "Back to mistake users", mistake_users_path %>
</div>

app/views/mistake_users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mistake users</h1>

<div id="mistake_users">
  <% @mistake_users.each do |mistake_user| %>
    <%= render mistake_user %>
    <p>
      <%= link_to "Show this mistake user", mistake_user %>
    </p>
  <% end %>
</div>

<%= link_to "New mistake user", new_mistake_user_path %>

app/views/mistake_users/new.html.erb
<h1>New mistake user</h1>

<%= render "form", mistake_user: @mistake_user %>

<br>

<div>
  <%= link_to "Back to mistake users", mistake_users_path %>
</div>

app/views/mistake_users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mistake_user %>

<div>
  <%= link_to "Edit this mistake user", edit_mistake_user_path(@mistake_user) %> |
  <%= link_to "Back to mistake users", mistake_users_path %>

  <%= button_to "Destroy this mistake user", @mistake_user, method: :delete %>
</div>

app/views/mistakes/_form.html.erb
<%= form_with(model: mistake) do |f| %>
  <% if mistake.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mistake.errors.count, "error") %> prohibited this mistake from being saved:</h2>

      <ul>
        <% mistake.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class="row">
    <div class="col-sm-1"><%= f.label :mistake %></div>
    <div class="col-sm-4"><%= f.text_field :name, class: "form-control" %></div>
  </div><br>
  <div class="row">
    <div class="col-sm-2"><%= f.label :description %></div>
    <div class="col-sm-4"><%= f.text_field :description, class: "form-control" %></div>
  </div><br>
  <div class="row">
    <div class="col-sm-1"><%= f.label :severity %></div>
    <div class="col-sm-4"><%= f.text_field :severity, class: "form-control" %></div>
  </div><br>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/mistakes/_mistake.html.erb
<div id="<%= dom_id mistake %>">
</div>

app/views/mistakes/edit.html.erb
<h1>Editing mistake</h1>

<%= render "form", mistake: @mistake %>

<br>

<div>
  <%= link_to "Show this mistake", @mistake %> |
  <%= link_to "Back to mistakes", mistakes_path %>
</div>

app/views/mistakes/index.html.erb
<div class='container'>
  <p style="color: green"><%= notice %></p>
  <h1>Mistakes</h1>
  <table class='table compact table-striped' id='mistakes' data-source='<%= mistakes_url(format: :json) %>'>
    <thead>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Severity</th>
      <th>Count</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </thead>
    <tbody>
    </tbody>
  </table>
  <%= link_to "New misake", new_mistake_path %>
</div>

app/views/mistakes/new.html.erb
<h1>New mistake</h1>

<%= render "form", mistake: @mistake %>

<br>

<div>
  <%= link_to "Back to mistakes", mistakes_path %>
</div>

app/views/mistakes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mistake %>
<h1>Mistake Details</h1>
<p><strong>Name:</strong> <%= @mistake.name %></p>
<p><strong>Description:</strong> <%= @mistake.description %></p>
<p><strong>Severity:</strong> <%= @mistake.severity %></p>
<p><strong>Count:</strong> <%= @mistake.users.count %></p>
<div>
  <%= link_to "Edit this mistake", edit_mistake_path(@mistake) %> |
  <%= link_to "Back to mistakes", mistakes_path %>
  

  <%= button_to "Destroy this mistake", @mistake, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-1"><%= f.label :user %></div>
    <div class="col-sm-4"><%= f.text_field :name, class: "form-control" %></div>
  </div><br>
  <div class="row">
    <div class="col-sm-1"><%= f.label :email %></div>
    <div class="col-sm-4"><%= f.text_field :email, class: "form-control" %></div>
  </div><br>

  <div>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<div class='container'>
  <h1>Editing <%= @user.name %></h1>

  <%= render "form", user: @user %>

  <br>

  <div>
    <%= link_to "Show this user", @user %> |
    <%= link_to "Back to users", users_path %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>
  <p style="color: green"><%= notice %></p>
  <h1>Users</h1>
  <table class='table compact table-striped' id='users' data-source='<%= users_url(format: :json) %>'>
    <thead>
      <th>ID</th>
      <th>Email</th>
      <th>Name</th>
      <th>Created At</th>
      <th>Mistakes</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </thead>
    <tbody>

    </tbody>
  </table>
  <%= link_to "New user", new_user_path %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>
<h1>User Details</h1>
<p><strong>Name:</strong> <%= @user.name %></p>
<p><strong>Email:</strong> <%= @user.email %></p>

<h1>Mistakes</h1>
<% if @user.mistakes.empty? %>
  <p>No mistakes found.</p>
<% else %>
<% @user.mistakes.each do |mistake| %>
<ul>
  <li><%= mistake.name %></li>
  </ul>
<% end %>
<% end %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>